add server

diff --git a/mfa-change-demo/run b/mfa-change-demo/run
--- a/mfa-change-demo/run
+++ b/mfa-change-demo/run
@@ -4,31 +4,34 @@
 set -ex
 
 echo "starting zookeeper"
-/usr/local/kafka/bin/zookeeper-server-start.sh zookeeper.properties > /dev/null 2>&1 &
+/usr/local/kafka/kafka_2.12-3.5.0/bin/zookeeper-server-start.sh /usr/local/kafka/kafka_2.12-3.5.0/config/zookeeper.properties > /dev/null 2>&1 &
 sleep 5
 lsof -i:2181  > /dev/null || {
   echo "failed to start zookeeper"
   exit 1
 }
 echo "zookeeper started. starting kafka"
-/usr/local/kafka/bin/kafka-server-start.sh kafka.properties > /dev/null 2>&1 &
+/usr/local/kafka/kafka_2.12-3.5.0/bin/kafka-server-start.sh /usr/local/kafka/kafka_2.12-3.5.0/config/server.properties > /dev/null 2>&1 &
 sleep 5
 lsof -i:9092 > /dev/null || {
   echo "kafka start failed"
   exit 1
 }
 
-/usr/local/kafka/bin/kafka-topics.sh --create --topic recwave --partitions 1 --replication-factor 1 --bootstrap-server=127.0.0.1:9092 \
+/usr/local/kafka/kafka_2.12-3.5.0/bin/kafka-topics.sh --create --topic recwave --partitions 1 --replication-factor 1 --bootstrap-server=127.0.0.1:9092 \
   --if-not-exists  > /dev/null 2>&1 || {
   echo "kafka topic creation failed"
   exit 1
 }
 sleep 3
 
-/risingwave/bin/risingwave playground > /dev/null &
+pip install risingwave 
+python3 server/udf.py > /dev/null 2>&1 &
 sleep 5
-
-python3 recommender/udf.py
+lsof -i:8815  > /dev/null || {
+  echo "failed to start udf"
+  exit 1
+}
 
 sleep 1
 
@@ -41,6 +44,6 @@ sleep 2
 export GENERATOR_PATH=generator
 
 python3 generator --num-users=15 \
-  --dump-users="$GENERATOR_PATH/users.json" \
+  --dump-users="$GENERATOR_PATH/users.json" 
 
 
